# eater/eat.py — 生吞活剥版（最终版：参数签名 + 正确转义）
"""Universal Eater — One plugin per library. One file. All functions. With parameter signatures."""

import sys
import importlib
import inspect
import json
from pathlib import Path

TEMPLATE = '''"""
{library_name} — all functions
Auto-generated by AICP Eater
"""

import {library_name}
import pkgutil
import inspect
import json

def help():
    """列出所有可调用的函数，含参数签名"""
    funcs = json.loads({func_names_json})
    details = json.loads({func_details_json})
    
    return {{
        "route": "/api/{library_name}",
        "total": {total_funcs},
        "functions": funcs,
        "function_details": details,
        "how_to_call": {{
            "example_payload": json.loads({example_payload_json}),
            "curl_example": {curl_example_json}
        }}
    }}

async def execute(envelop, agent):
    try:
        func_name = envelop.meta.get("function")
        if not func_name:
            envelop.payload["error"] = "Missing function name in meta.function"
            return envelop
        
        func = getattr({library_name}, func_name, None)
        if func is None:
            for _, mod_name, _ in pkgutil.iter_modules({library_name}.__path__):
                try:
                    mod = __import__(f"{{library_name}}.{{mod_name}}", fromlist=[func_name])
                    func = getattr(mod, func_name, None)
                    if func is not None:
                        break
                except:
                    pass
        
        if func is None:
            envelop.payload["error"] = f"{{func_name}} not found in {library_name}"
            return envelop
        
        result = func(**envelop.payload.get("args", {{}}))
        envelop.payload["result"] = str(result)
        envelop.payload["source"] = "{library_name}"
    except Exception as e:
        envelop.payload["error"] = str(e)
    return envelop
'''


def main():
    if len(sys.argv) < 2:
        print("Usage: python eater/eat.py <library>")
        print("Example: python eater/eat.py pandas")
        return

    library_name = sys.argv[1]
    import_name = library_name.replace("-", "_")
    
    try:
        lib = importlib.import_module(import_name)
    except ImportError:
        print(f"❌ {import_name} not installed. pip install {library_name}")
        return

    # 数函数 + 提取参数签名
    func_details = []
    func_names = []
    for f in dir(lib):
        if f.startswith("_"):
            continue
        obj = getattr(lib, f, None)
        if obj is None or not callable(obj):
            continue
        func_names.append(f)
        try:
            sig = inspect.signature(obj)
            params = {}
            for k, v in sig.parameters.items():
                if v.default is inspect.Parameter.empty:
                    params[k] = "<required>"
                else:
                    params[k] = str(v.default)
        except (ValueError, TypeError):
            params = {}
        func_details.append({"name": f, "params": params})
    
    total = len(func_names)
    
    # 找第一个有参数的函数做示例
    example_name = func_names[0] if func_names else "func_name"
    example_params = {}
    for fd in func_details:
        if fd["params"]:
            example_name = fd["name"]
            example_params = fd["params"]
            break
    
    example_payload = {"function": example_name, "args": example_params}
    example_payload_str = json.dumps(example_payload, ensure_ascii=False)
    curl_example = f"curl -X POST /api/{import_name} -d '{example_payload_str}'"
    
    # 生成插件
    output_file = Path("plugins") / f"{import_name}.py"
    plugin_code = TEMPLATE.format(
        library_name=import_name,
        func_names_json=json.dumps(json.dumps(func_names[:200], ensure_ascii=False)),
        func_details_json=json.dumps(json.dumps(func_details[:200], ensure_ascii=False)),
        total_funcs=total,
        example_payload_json=json.dumps(json.dumps(example_payload, ensure_ascii=False)),
        curl_example_json=json.dumps(curl_example, ensure_ascii=False),
    )
    output_file.write_text(plugin_code, encoding="utf-8")

    print(f"🎯 plugins/{import_name}.py")
    print(f"   {total} functions. One plugin. All callable.")
    print(f"   POST /api/{import_name}")
    print(f"   AI knows the params. Humans too.")


if __name__ == "__main__":
    main()