# eater/eat_pil.py — PIL 专享版（最终修复：用 repr 绕过 JSON 转义）
"""Deep scan PIL/Pillow — all sub-modules, all callables, with parameter signatures."""

import importlib
import pkgutil
import inspect
import json
from pathlib import Path

LIBRARY = "PIL"
OUTPUT_FILE = Path("plugins") / f"{LIBRARY}.py"

def deep_scan():
    lib = importlib.import_module(LIBRARY)
    funcs = []

    for _, mod_name, _ in pkgutil.iter_modules(lib.__path__):
        try:
            mod = importlib.import_module(f"{LIBRARY}.{mod_name}")
            for name in dir(mod):
                if name.startswith("_"):
                    continue
                obj = getattr(mod, name, None)
                if obj is None:
                    continue
                if inspect.isclass(obj) or inspect.isfunction(obj):
                    funcs.append((mod_name, name))
            if hasattr(mod, "__path__"):
                for _, sub_name, _ in pkgutil.iter_modules(mod.__path__):
                    try:
                        sub_mod = importlib.import_module(f"{LIBRARY}.{mod_name}.{sub_name}")
                        for name in dir(sub_mod):
                            if name.startswith("_"):
                                continue
                            obj = getattr(sub_mod, name, None)
                            if obj is None:
                                continue
                            if inspect.isclass(obj) or inspect.isfunction(obj):
                                funcs.append((f"{mod_name}.{sub_name}", name))
                    except:
                        pass
        except:
            pass

    return sorted(set(funcs))

def generate():
    funcs = deep_scan()
    
    func_names = [f"{m}.{n}" for m, n in funcs]
    func_details = []
    for m, n in funcs:
        try:
            mod = importlib.import_module(f"{LIBRARY}.{m}")
            obj = getattr(mod, n, None)
            if obj:
                try:
                    sig = inspect.signature(obj)
                    params = {}
                    for k, v in sig.parameters.items():
                        if v.default is inspect.Parameter.empty:
                            params[k] = "<required>"
                        else:
                            params[k] = str(v.default)
                except (ValueError, TypeError):
                    params = {}
            else:
                params = {}
        except:
            params = {}
        func_details.append({"name": f"{m}.{n}", "params": params})
    
    # 用 repr 生成 Python 原生列表，绕过 JSON 转义
    func_names_py = repr(func_names[:200])
    func_details_py = repr(func_details[:200])
    
    # 取第一个有参数的函数做示例
    example_name = func_names[0] if func_names else "Image.open"
    example_params = func_details[0]["params"] if func_details else {}
    parts = example_name.split(".")
    example_fn = parts[-1]
    example_mod = ".".join(parts[:-1])
    
    example_payload = {"function": example_fn, "module": example_mod, "args": example_params}
    
    code = f'''"""
{LIBRARY} — all functions (deep scan)
Auto-generated by AICP Eater
"""

import {LIBRARY}
import pkgutil
import inspect

def help():
    """列出所有可调用的函数和类，含参数签名"""
    funcs = {func_names_py}
    details = {func_details_py}
    
    return {{
        "route": "/api/{LIBRARY}",
        "total": {len(funcs)},
        "functions": funcs,
        "function_details": details,
        "how_to_call": {{
            "description": "PIL functions live in sub-modules. Use 'function' for the function name and 'module' for its parent module. Check 'function_details' for parameter names.",
            "example_payload": {json.dumps(example_payload, ensure_ascii=False)},
            "curl_example": {json.dumps(f"curl -X POST /api/{LIBRARY} -d '{json.dumps(example_payload)}'", ensure_ascii=False)}
        }}
    }}

async def execute(envelop, agent):
    try:
        func_name = envelop.meta.get("function")
        if not func_name:
            envelop.payload["error"] = "Missing function name in meta.function"
            return envelop
        
        module = envelop.meta.get("module", "")
        
        if module:
            try:
                mod = __import__(f"{LIBRARY}.{{module}}", fromlist=[func_name])
                func = getattr(mod, func_name, None)
            except:
                func = None
        else:
            func = getattr({LIBRARY}, func_name, None)
        
        if func is None:
            for _, mod_name, _ in pkgutil.iter_modules({LIBRARY}.__path__):
                try:
                    mod = __import__(f"{LIBRARY}.{{mod_name}}", fromlist=[func_name])
                    func = getattr(mod, func_name, None)
                    if func is not None:
                        module = mod_name
                        break
                except:
                    pass
        
        if func is None:
            envelop.payload["error"] = f"{{func_name}} not found in {LIBRARY}"
            return envelop
        
        if inspect.isclass(func):
            args = envelop.payload.get("args", {{}})
            try:
                instance = func(**args)
            except:
                instance = func()
            envelop.payload["result"] = str(instance)
        else:
            result = func(**envelop.payload.get("args", {{}}))
            envelop.payload["result"] = str(result)
        
        envelop.payload["source"] = "{LIBRARY}"
    except Exception as e:
        envelop.payload["error"] = str(e)
    return envelop
'''

    OUTPUT_FILE.write_text(code, encoding="utf-8")
    print(f"🎯 {OUTPUT_FILE}")
    print(f"   {len(funcs)} functions deep-scanned with parameter signatures")

if __name__ == "__main__":
    generate()